name: Auto Publish
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/echoapp:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/echoapp:${{ github.sha }}

    - name: 'Publish to IHFKluster'
      run: |
              git clone https://user:${{ secrets.IHFKLUSTER_GITHUB_TOKEN }}@github.com/TylerIHF/IHFKluster.git
              cd IHFKluster
              git config user.name "Publish to IHFKluster"
              git config user.email "action@tylerihf.github.io"
              sed -E 's/azurecr\.io\/echoapp:.*$/azurecr\.io\/echoapp:${{ github.sha }}/' -i clusters/202FDF7A2DA04398A03073AFEFBE532C/production/echo-app.yaml
              sed -E 's/azurecr\.io\/echoapp:.*$/azurecr\.io\/echoapp:${{ github.sha }}/' -i clusters/202FDF7A2DA04398A03073AFEFBE532C/development/echo-app.yaml
              git commit -a -m "Auto Publish EchoApp ${{ github.sha }}"
              git push
